### ISSUE TITLE
Using commands that change the config file seems to crash the program on 1.9.1

### ISSUE THREAD

**Issue by Gameskiller01** [Aethese/Switchence#12] opened 2022-01-25 16:20 UTC
When either attempting to add a game to the favourites list, or attempting to change the friend code, the program will crash on 1.9.1, and it will continually crash every time the program is loaded after that until the config.json file is deleted. Tested on both Ubuntu 21.10 with Python 3.9.7 and Windows 10 using the .exe file. When looking in the config file after running these commands it's completely blank, which I suspect is the cause of the issue. Issue does not occur on 1.9.0 and config file can be changed just fine.

**Comment by Aethese** [comment] 2022-01-25 16:57
Thanks for bringing this up with me! I never realised this was an issue. I think I know the root cause so I will bring a fix out ASAP!

**Comment by Aethese** [comment] 2022-01-26 13:31
I have fixed the issue locally and I will bring out v1.9.2 that will fix this issue soon. I will close this issue when I published v1.9.2. Thanks for using Switchence!

**Comment by Aethese** [comment] 2022-01-28 12:07
v1.9.2 released!

**Closed by Aethese** 2022-01-28 12:07 UTC
